$(document).ready(function(){
    $('#docHide').click(function(){
        $('#doc').toggle();
    });
    $('#webHide').click(function(){
        $('#webpage').toggle();
    });
    $('#webHide2').click(function(){
        $('#webpage2').toggle();
    });
});